version: '3'
services:
  web:
    image: ubuntu:latest
    command: bash -c 'cd /srv && ./dnslogger'
    depends_on:
      - db
    restart: always
    volumes:
      - ./dnslogger:/srv/dnslogger
    ports:
      - "53:53/udp"
      - "1965:1965/tcp"