version: '3'
services:
  web:
    image: ubuntu:latest
    command: bash -c 'cd /srv && ./dnslogger'
    restart: always
    volumes:
      - ./dnslogger:/srv/dnslogger
      - ./config.default.ini:/srv/config.default.ini
    ports:
      - "53:53/udp"
      - "2020:2020/tcp"
